service: aws-sls-project

provider:
  name: aws
  runtime: nodejs12.x
  profile: SahejAWS

plugins:
  - serverless-s3-sync
  - serverless-webpack

package:
  individually: true

custom:
  s3Sync:
    - bucketName: aws-sls-project-demo-upload-bucket-123987
      localDir: UploadData

functions:
  getUser:
    handler: functions/getUser.handler
    events:
      - http:
          path: get-user/{ID}
          method: GET
          cors: true

resources:
  Resources:
    DemoBucketUpload:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: aws-sls-project-demo-upload-bucket-123987
