service: aws-sls-project

provider:
  name: aws
  runtime: nodejs12.x
  profile: SahejAWS
  iamRoleStatements:
    - Effect: Allow
      Action:
        - comprehend:*
        - ses:*
      Resource: "*"

functions:
  analyse:
    handler: functions/endpoints/analyse.handler
    events:
      - http:
          path: analyse
          method: POST
          cors: true
  sendReminder:
    handler: functions/scheduleTasks/reminderEmail.handler
    events:
      - schedule: cron(0 9 ? * 7 *)
